
'use server';
/**
 * @fileOverview A Genkit flow to summarize conversation context.
 *
 * - summarizeConversation - Generates a summary of the conversation.
 * - SummarizeConversationInput - Input schema for the summarization flow.
 * - SummarizeConversationOutput - Output schema for the summarization flow.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

// Define schemas internally
const InternalSummarizeConversationInputSchema = z.object({
  conversationContext: z.object({
    previousSummaryText: z.string().optional().describe("The summary from the previous turn, if any."),
    latestQueryText: z.string().describe("The most recent user query."),
    latestSpecialistOutputText: z.string().optional().describe("The most recent specialist output, if relevant to the last query."),
    latestSynthesizerResponseText: z.string().describe("The AI's latest response to the user."),
  }),
});
export type SummarizeConversationInput = z.infer<typeof InternalSummarizeConversationInputSchema>;

const InternalSummarizeConversationOutputSchema = z.object({
  summaryText: z.string().describe('The generated concise summary of the conversation.'),
});
export type SummarizeConversationOutput = z.infer<typeof InternalSummarizeConversationOutputSchema>;

export async function summarizeConversation(input: SummarizeConversationInput): Promise<SummarizeConversationOutput> {
  console.log('[summarizeConversation exported function] ENTERED. Input received for summarization.');
  try {
    const result = await summarizeConversationGenkitFlow(input);
    if (result && result.summaryText) {
        console.log(`[summarizeConversation exported function] Summary successfully generated by Genkit flow: "${result.summaryText.substring(0,70)}..."`);
    } else {
        console.warn('[summarizeConversation exported function] Genkit flow did not return valid summary text.');
    }
    return result;
  } catch (error) {
    const typedError = error as Error;
    console.error(
      "[summarizeConversation exported function] CRITICAL ERROR DURING SUMMARIZATION. Input received, Error_Name:", typedError.name,
      "Error_Message:", typedError.message, "Error_Stack:", typedError.stack,
      "Full_Error_Object:", JSON.stringify(error, Object.getOwnPropertyNames(error))
    );
    return { summaryText: "" }; // Return empty summary on error
  }
}

const summarizationPrompt = ai.definePrompt({
  name: 'summarizeConversationPrompt',
  input: { schema: InternalSummarizeConversationInputSchema.shape.conversationContext },
  output: { schema: InternalSummarizeConversationOutputSchema },
  prompt: `Generate a concise summary of the conversation to provide context for future responses, capturing all discussed topics, companies (e.g., MSFT, AAPL), key metrics (e.g., revenue, P/E ratio), insights (e.g., management outlook, risks), industries (e.g., tech, retail), and general queries (e.g., financial literacy). Use the provided conversation data:
Previous Summary (if any): {{{previousSummaryText}}}
User Query: {{{latestQueryText}}}
Specialist Output (if any): {{{latestSpecialistOutputText}}}
AI Response: {{{latestSynthesizerResponseText}}}
Keep the summary under 1000 characters, adjusting length to cover all relevant context (e.g., longer for multiple stocks/industries, shorter for single-topic discussions).`,
  config: {
    // model: 'gemini-2.0-flash-001', // Removed: Model should be inherited from the ai instance or generate call
    temperature: 0.1,
    maxOutputTokens: 250,
    safetySettings: [
      { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_NONE' },
      { category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT', threshold: 'BLOCK_NONE' },
      { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_NONE' },
      { category: 'HARM_CATEGORY_DANGEROUS_CONTENT', threshold: 'BLOCK_NONE' },
    ],
  },
});

const summarizeConversationGenkitFlow = ai.defineFlow(
  {
    name: 'summarizeConversationGenkitFlow',
    inputSchema: InternalSummarizeConversationInputSchema,
    outputSchema: InternalSummarizeConversationOutputSchema,
  },
  async (input: SummarizeConversationInput): Promise<SummarizeConversationOutput> => {
    console.log('[summarizeConversationGenkitFlow] Processing summarization prompt.');

    const { output } = await summarizationPrompt(input.conversationContext);

    if (!output || typeof output.summaryText === 'undefined' || output.summaryText.trim() === "") {
      console.warn("[summarizeConversationGenkitFlow] AI flow did not produce a valid summary text. Output from AI:", output);
      return { summaryText: "" };
    }
    console.log('[summarizeConversationGenkitFlow] Summary text generated.');
    return output;
  }
);

